package io.slgl.template;

class UnicodeToASCIIUtil {

    static String escapeToAscii(char character) {
        switch (character) {

            case '\u00AB':
            case '\u00BB':
            case '\u301E':
            case '\u301D':
            case '\u3003':
            case '\u2036':
            case '\u2033':
            case '\u201F':
            case '\u201E':
            case '\u201D':
            case '\u201C':
            case '\u030E':
            case '\u030B':
            case '\u02BA':
                return "\"";

            case '\u00AD':
            case '\u2212':
            case '\u2014':
            case '\u2013':
            case '\u2012':
            case '\u2011':
            case '\u2010':
                return "-";

            case '\u00B4':
            case '\u201B':
            case '\u2019':
            case '\u2018':
            case '\u0301':
            case '\u02C8':
            case '\u02BC':
            case '\u02B9':
            case '\u2032':
                return "'";

            case '\u00F7':
                return "/";
            case '\u01C0':
                return "|";
            case '\u01C3':
                return "!";
            case '\u02C4':
                return "^";
            case '\u02C6':
                return "^";
            case '\u02CB':
                return "`";
            case '\u02CD':
                return "_";
            case '\u02DC':
                return "~";
            case '\u0300':
                return "`";
            case '\u0302':
                return "^";
            case '\u0303':
                return "~";
            case '\u0331':
                return "_";
            case '\u0332':
                return "_";
            case '\u0338':
                return "/";
            case '\u0589':
                return ":";
            case '\u05C0':
                return "|";
            case '\u05C3':
                return ":";
            case '\u066A':
                return "%";
            case '\u066D':
                return "*";
            case '\u200B':
                return " ";
            case '\u2015':
                return "--";
            case '\u2016':
                return "||";
            case '\u2017':
                return "_";
            case '\u201A':
                return ",";
            case '\u2034':
                return "''";
            case '\u2035':
                return "`";
            case '\u2037':
                return "''";
            case '\u2038':
                return "^";
            case '\u2039':
                return "<";
            case '\u203A':
                return ">";
            case '\u203D':
                return "?";
            case '\u2044':
                return "/";
            case '\u204E':
                return "*";
            case '\u2052':
                return "%";
            case '\u2053':
                return "~";
            case '\u2060':
                return " ";
            case '\u20E5':
                return "\\";
            case '\u2215':
                return "/";
            case '\u2216':
                return "\\";
            case '\u2217':
                return "*";
            case '\u2223':
                return "|";
            case '\u2236':
                return ":";
            case '\u223C':
                return "~";
            case '\u2264':
                return "<=";
            case '\u2265':
                return ">=";
            case '\u2266':
                return "<=";
            case '\u2267':
                return ">=";
            case '\u2303':
                return "^";
            case '\u2329':
                return "<";
            case '\u232A':
                return ">";
            case '\u266F':
                return "#";
            case '\u2731':
                return "*";
            case '\u2758':
                return "|";
            case '\u2762':
                return "!";
            case '\u27E6':
                return "[";
            case '\u27E8':
                return "<";
            case '\u27E9':
                return ">";
            case '\u2983':
                return "{";
            case '\u2984':
                return "}";
            case '\u3008':
                return "<";
            case '\u3009':
                return ">";
            case '\u301B':
                return "]";
            case '\u301C':
                return "~";
            case '\uFEFF':
                return " ";
        }
        return null;
    }
}
